name: Swift Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and Test macOS App
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'

    - name: Show versions
      run: |
        xcodebuild -version
        swift --version
        
    - name: Build application
      run: |
        xcodebuild -project BetterTab/BetterTab.xcodeproj -scheme BetterTab -destination 'platform=macOS' CODE_SIGNING_ALLOWED=NO

    - name: Run tests
      run: |
        xcodebuild -project BetterTab/BetterTab.xcodeproj -scheme BetterTab -destination 'platform=macOS'

