name: Swift Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and Test macOS App
    runs-on: macos-13 # macos-latest currently maps to macOS 13 with Xcode 15.2 (as of May 2025)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Select Xcode 16.2
      run: |
        sudo xcode-select -s /Applications/Xcode_16.2.app
        xcodebuild -version
        swift --version

    - name: Print Deployment Target
      run: |
        xcodebuild -project BetterTab/BetterTab.xcodeproj \
          -scheme BetterTab \
          -showBuildSettings | grep MACOSX_DEPLOYMENT_TARGET

    - name: Build application
      run: |
        xcodebuild \
          -project BetterTab/BetterTab.xcodeproj \
          -scheme BetterTab \
          -destination 'platform=macOS' \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY=""

    - name: Run tests
      run: |
        xcodebuild \
          -project BetterTab/BetterTab.xcodeproj \
          -scheme BetterTab \
          -destination 'platform=macOS' \
          test \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY=""
